Repository bellshade/cppSourceCode, pull requests merged in 2021-01, with the labels that each got.

#1 Create cppDataType.cpp
  cppDataType.cpp
Labels: Ok to merge

#2 vignere chipers with namespace
  cryptograph/vignere_chiper.cpp
Labels: Ok to merge

#3 update size repo
  README.md
Labels: Ok to merge

#4 rabin karp imlementation
  string/rabin_karp.cpp
Labels: Ok to merge

#13 huffman implementation
  algorithm/greedy/huffman.cpp
Labels: Ok to merge

#14 game menu of snake game
  sfml/snakeGame/include/GameMenu/GameMenu.h
Labels: Ok to merge

#15 main menu header
  sfml/snakeGame/src/UI/MainMenu.h
Labels: Ok to merge

#16 Create egine.h
  sfml/snakeGame/src/Game-core/egine.h
Labels: Ok to merge, passed !

#17 food
  sfml/snakeGame/src/Game-core/food.h
Labels: Ok to merge, passed !

#21 Create snake.h
  sfml/snakeGame/src/Game-core/snake.h
Labels: Ok to merge, passed !

#22 create snake.cpp
  sfml/snakeGame/src/Game-core/snake.cpp
Labels: Ok to merge, passed !

#20 Create game.cpp
  sfml/snakeGame/src/Game-core/game.cpp
Labels: Ok to merge, passed !

#19 create game.h
  sfml/snakeGame/src/Game-core/game.h
Labels: Ok to merge, passed !

#18 create food
  sfml/snakeGame/src/Game-core/food.cpp
Labels: Ok to merge, passed !

#24 update
  README.md
Labels: Ok to merge

#25 make hunter
  sfml/zombieV/src/Hunter.cpp
Labels: Ok to merge

#26 create hunter
  sfml/zombieV/src/Hunter.cpp
Labels: Ok to merge

#27 create system bot
  sfml/zombieV/src/Bot.cpp
Labels: Ok to merge

#28 create gameworld
  sfml/zombieV/src/System/GameWorld.cpp
Labels: Ok to merge

#29 hunter base
  sfml/zombieV/src/HunterBase.cpp
Labels: Ok to merge

#34 Create Bot.hpp
  sfml/zombieV/src/include/Bot.hpp
Labels: Ok to merge

#30 create zombie
  sfml/zombieV/src/Zombie.cpp
Labels: Ok to merge

#32 game render
  sfml/zombieV/src/System/GameRender.cpp
Labels: Ok to merge

#37 turret
  sfml/zombieV/src/include/Turret.hpp
Labels: Ok to merge

#38 zombie
  sfml/zombieV/src/include/Zombie.hpp
Labels: Ok to merge

#35 Create Hunter.hpp
  sfml/zombieV/src/include/Hunter.hpp
Labels: Ok to merge

#36 Create HunterBase.hpp
  sfml/zombieV/src/include/HunterBase.hpp
Labels: Ok to merge

#31 create animation
  sfml/zombieV/src/System/Animation.cpp
Labels: Ok to merge

#39 bot.hpp
  sfml/zombieV/include/bot.hpp
Labels: Ok to merge

#41 hunter base
  sfml/zombieV/include/HunterBase.hpp
Labels: Ok to merge

#43 zombie
  sfml/zombieV/include/Zombie.hpp
Labels: Ok to merge

#45 create blur
  sfml/zombieV/include/Blur/blur.frag
Labels: Ok to merge

#50 explosion provider
  sfml/zombieV/include/Props/ExplosionProvider.hpp
Labels: Ok to merge

#58 wall
  sfml/zombieV/include/Props/Wall.hpp
Labels: Ok to merge

#60 configuration
  sfml/zombieV/include/System/Config.hpp
Labels: Ok to merge

#62 Create EntityTypes.hpp
  sfml/zombieV/include/System/EntityTypes.hpp
Labels: Ok to merge

#59 wood box
  sfml/zombieV/include/Props/WoodBox.hpp
Labels: Ok to merge

#71 standart entity
  sfml/zombieV/include/System/StandardEntity.hpp
Labels: Ok to merge

#70 sound player
  sfml/zombieV/include/System/SoundPlayer.hpp
Labels: Ok to merge

#66 grapich utils
  sfml/zombieV/include/System/GraphicsUtils.hpp
Labels: Ok to merge

#57 smoke
  sfml/zombieV/include/Props/Smoke.hpp
Labels: Ok to merge

#64 game render
  sfml/zombieV/include/System/GameRender.hpp
Labels: Ok to merge

#53 props
  sfml/zombieV/include/Props/Props.hpp
Labels: Ok to merge

#52 guts
  sfml/zombieV/include/Props/Guts.hpp
Labels: Ok to merge

#51 fire
  sfml/zombieV/include/Props/Fire.hpp
Labels: Ok to merge

#40 hunter
  sfml/zombieV/include/Hunter.hpp
Labels: Ok to merge

#48 explosion
  sfml/zombieV/include/Props/Explosion.hpp
Labels: Ok to merge

#47 bullet shell
  sfml/zombieV/include/Props/BulletShell.hpp
Labels: Ok to merge

#42 turret
  sfml/zombieV/include/Turret.hpp
Labels: Ok to merge

#46 light egine
  sfml/zombieV/include/LightEngine/LightEngine.hpp
Labels: Ok to merge

#49 shadow caster
  sfml/zombieV/include/LightEngine/ShadowCaster.hpp
Labels: Ok to merge

#56 chained object
  sfml/zombieV/include/System/ChainedObject.hpp
Labels: Ok to merge

#44 dynamical blurring
  sfml/zombieV/include/Blur/DynamicBlur.h
Labels: Ok to merge, passed !

#68 life form
  sfml/zombieV/include/System/LifeForm.hpp
Labels: Ok to merge, passed !

#69 pool object
  sfml/zombieV/include/System/PoolObject.hpp
Labels: Ok to merge, passed !

#61 cooldown
  sfml/zombieV/include/System/Cooldown.hpp
Labels: Ok to merge, passed !

#74 world entity pool
  sfml/zombieV/include/System/WorldEntityPool.hpp
Labels: Ok to merge, passed !

#73 world entity
  sfml/zombieV/include/System/WorldEntity.hpp
Labels: Ok to merge, passed !

#72 utils
  sfml/zombieV/include/System/Utils.hpp
Labels: Ok to merge, passed !

#54 animation
  sfml/zombieV/include/System/Animation.hpp
Labels: Ok to merge, passed !

#67 level
  sfml/zombieV/include/System/Level.hpp
Labels: Ok to merge, passed !

#65 game world
  sfml/zombieV/include/System/GameWorld.hpp
Labels: Ok to merge, passed !

#63 event manager
  sfml/zombieV/include/System/EventManager.hpp
Labels: Ok to merge, passed !

#55 auto aim
  sfml/zombieV/include/System/AutoAim.hpp
Labels: Ok to merge, passed !

#75 types
  sfml/zombieV/include/UnitedEngine/Types.hpp
Labels: Ok to merge

#79 united engine
  sfml/zombieV/include/UnitedEngine/UnitedEngine.h
Labels: Ok to merge

#77 collision manager
  sfml/zombieV/include/UnitedEngine/U_2DCollisionManager.h
Labels: Ok to merge, passed !

#80 Create Vec2.h
  sfml/zombieV/include/UnitedEngine/Vec2.h
Labels: Ok to merge, passed !

#78 2d constraint
  sfml/zombieV/include/UnitedEngine/U_2DConstraint.h
Labels: Ok to merge, passed !

#76 Create U_2DBody.h
  sfml/zombieV/include/UnitedEngine/U_2DBody.h
Labels: Ok to merge

#83 create weapons
  sfml/zombieV/include/Weapons/Weapons.hpp
Labels: Ok to merge

#87 bullet
  sfml/zombieV/include/Weapons/Bullet.hpp
Labels: Ok to merge

#85 shotgun weapon
  sfml/zombieV/include/Weapons/Shotgun.hpp
Labels: Ok to merge

#84 weapon
  sfml/zombieV/include/Weapons/Weapon.hpp
Labels: Ok to merge

#91 Create blur.frag
  sfml/zombieV/src/Blur/blur.frag
Labels: Ok to merge

#90 Create DynamicBlur.cpp
  sfml/zombieV/src/Blur/DynamicBlur.cpp
Labels: Ok to merge

#89 turret base
  sfml/zombieV/include/Weapons/Turrets/TurretBase.hpp
Labels: Ok to merge

#88 create Ak
  sfml/zombieV/include/Weapons/Ak.hpp
Labels: Ok to merge

#86 pistol
  sfml/zombieV/include/Weapons/Pistol.hpp
Labels: Ok to merge

#94 update information wikipedia
  README.md
Labels: Ok to merge, passed !

#95 update content
  README.md
Labels: Ok to merge, passed !

#97 bullet shell
  sfml/zombieV/src/Props/BulletShell.cpp
Labels: Ok to merge

#102 Create Smoke.cpp
  sfml/zombieV/src/Props/Smoke.cpp
Labels: Ok to merge

#106 Create EventManager.cpp
  sfml/zombieV/src/System/EventManager.cpp
Labels: Ok to merge

#103 Create Wall.cpp
  sfml/zombieV/src/Props/Wall.cpp
Labels: Ok to merge

#105 Create Cooldown.cpp
  sfml/zombieV/src/System/Cooldown.cpp
Labels: Ok to merge

#101 Create Guts.cpp
  sfml/zombieV/src/Props/Guts.cpp
Labels: Ok to merge

#107 Create GraphicsUtils.cpp
  sfml/zombieV/src/System/GraphicsUtils.cpp
Labels: Ok to merge

#104 Create AutoAim.cpp
  sfml/zombieV/src/System/AutoAim.cpp
Labels: Ok to merge

#100 Create Fire.cpp
  sfml/zombieV/src/Props/Fire.cpp
Labels: Ok to merge

#98 explosion
  sfml/zombieV/src/Props/Explosion.cpp
Labels: Ok to merge

#99 Create ExplosionProvider.cpp
  sfml/zombieV/src/Props/ExplosionProvider.cpp
Labels: Ok to merge

#96 Create ShadowCaster.cpp
  sfml/zombieV/src/LightEngine/ShadowCaster.cpp
Labels: Ok to merge

#108 level
  sfml/zombieV/src/System/Level.cpp
Labels: Ok to merge, enhancement

#112 Create U_2DCollisionManager.cpp
  sfml/zombieV/src/UnitedEngine/U_2DCollisionManager.cpp
Labels: Ok to merge, enhancement

#116 reconfiguration hunter base
  sfml/zombieV/src/HunterBase.cpp
Labels: Ok to merge, enhancement

#115 hunter reconfiguration
  sfml/zombieV/src/Hunter.cpp
Labels: Ok to merge, enhancement

#109 life form
  sfml/zombieV/src/System/LifeForm.cpp
Labels: Ok to merge, enhancement

#114 Create Vec2.cpp
  sfml/zombieV/src/UnitedEngine/Vec2.cpp
Labels: Ok to merge, enhancement

#113 Create U_2DConstraint.cpp
  sfml/zombieV/src/UnitedEngine/U_2DConstraint.cpp
Labels: Ok to merge, enhancement

#111 world entity
  sfml/zombieV/src/System/WorldEntity.cpp
Labels: Ok to merge, enhancement

#110 utils
  sfml/zombieV/src/System/Utils.cpp
Labels: Ok to merge, enhancement

#125 integer to roman
  integer_to_roman.cpp
Labels: Ok to merge, enhancement, passed !

#122 enhancement
  chipers/caesar_chiper.cpp
  integer_to_roman.cpp
Labels: Ok to merge, enhancement

#126 Create decimal_to_roman_numeral.cpp
  decimal_to_roman_numeral.cpp
Labels: Ok to merge, enhancement

#129 matrix exponent
  other/matrix_exponent.cpp
Labels: Ok to merge, enhancement

#132 pascal triangle
  other/pascal_triangle.cpp
Labels: Ok to merge, enhancement

#131 parenthesis matching
  other/parenthesis_matching.cpp
Labels: Ok to merge, enhancement

#130 Create palindrome_of_number.cpp
  other/palindrome_of_number.cpp
Labels: Ok to merge, enhancement

#128 Create happy_number.cpp
  other/happy_number.cpp
Labels: Ok to merge, enhancement

#133 postfix evaluation
  other/postifx_eval.cpp
Labels: Ok to merge

#134 Create primality_test.cpp
  other/primality_test.cpp
Labels: Ok to merge

#137 Create spiral_matrix.cpp
  other/spiral_matrix.cpp
Labels: Ok to merge

#136 Create sparse_matrix.cpp
  other/sparse_matrix.cpp
Labels: Ok to merge

#138 Create stairs_pattern.cpp
  other/stairs_pattern.cpp
Labels: Ok to merge

#135 Create smallest_circle.cpp
  other/smallest_circle.cpp
Labels: Ok to merge

#139 Create vector_function.cpp
  other/vector_function.cpp
Labels: Ok to merge

#140 Create horspool.cpp
  string/horspool.cpp
Labels: Ok to merge

#141 Create knuth_morris_prat.cpp
  string/knuth_morris_prat.cpp
Labels: Ok to merge

#143 New update patch
  README.md
  fast_integer_input.cpp
  numerical_method/bisection_method.cpp
  numerical_method/brent_method.cpp
  numerical_method/brent_method_extrema.cpp
  numerical_method/durand_kerner_roots.cpp
  other/happy_number.cpp
  other/matrix_exponent.cpp
  other/palindrome_of_number.cpp
  other/parenthesis_matching.cpp
  other/pascal_triangle.cpp
  other/postifx_eval.cpp
  other/primality_test.cpp
  other/smallest_circle.cpp
  other/sparse_matrix.cpp
  other/spiral_matrix.cpp
  other/stairs_pattern.cpp
  other/vector_function.cpp
  string/brute_force_string_searching.cpp
Labels: Ok to merge
